# This is a basic workflow that is manually triggered
name: Test reminder

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_commentary:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: test customized action
        id: myjsaction
        uses: cttan68/js-action@v1.o
        with:
          name-of-you: 'Pushpa'
      # Use the output from the `myjsaction` step
      - name: Get the output message time
        run: echo "The time was ${{ steps.myjsaction.outputs.time }}" 

      - name: Webhook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: "http://amberisgreat.ngrok.io/api/test_pedant"
          webhook_type: "json"
          data: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.pull_request.created_at}}", "updated_at": "${{github.event.pull_request.updated_at}}" }'
